baseurl = "/"
languageCode = "fr-FR"
languageLang = "fr"
theme = "hugo-icon"
title = "CDesign - Cabinet d'architecture"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[taxonomies]
  realisation = "realisations"

# Metadata
[params]
  author = "Johan Coupeau et Sandra Leong"
  description = "Architecture d'intérieur - Construction - Maitrise d'oeuvre"

# Navigation section
[params.nav]
  mission = "Présentation"
  services = "Réalisations"
  team = "L'équipe"
  contact = "Contact"
  # Include logo instead if HOME:
  home = "Accueil"
  # logo = "img/logo.png"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "/img/portfolio/concrete.png"
    [[params.mission.images.list]]
      img = "img/portfolio/escalier.png"
    [[params.mission.images.list]]
      img = "img/portfolio/renovation.png"
    [[params.mission.images.list]]
      img = "img/portfolio/salon.png"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Nos services"
    subtitle = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate laborum sapiente officiis molestiaea."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Nous contacter</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Nos valeurs"
    subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p> <ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Nous contacter</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Nos garanties"
    subtitle = "Magnam iste obcaecati illo laboriosam amet. Dignissimos sed quis voluptatum corporis adipisci amet."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore illum expedita placeat debitis, dignissimos obcaecati et modi. Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Nous contacter</a></p>"

# Services section
[params.services]
  enable = true
  video = true
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Nos Réalisations"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-present"
    title = "Web Development"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Retina Ready"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Light Speed"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Copyrighting"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Load Fast"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Work section
[params.work]
  enable = true

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/concrete.png"

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/salon2.png"

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/chic.png"

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/escalier.png"

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/renovation.png"

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/salon.png"

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/salon2.png"

  [[params.work.item]]
    title = "Titre"
    subtitle = "sous-titre"
    img = "img/portfolio/concrete.png"

# Team section
[params.team]
  enable = true
  title = "Notre équipe"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Johan Coupeau"
    position = "Architecte"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "img/johan.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"

  [[params.team.item]]
    name = "Sandra Leong"
    position = "Architecte"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "img/sandra.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  # [[params.team.item]]
  #   name = "John Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Nous contacter"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. Tous droits réservés. <br> Design par <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Images démo: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port par <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  facebook = "https://www.facebook.com/cdesignarchi"
  email = "mailto:contact@cdesignarchitectes.fr"
  instagram = "https://www.instagram.com/cdesign.architecte/"
